version: '3.1'
services:
  app:
    container_name: springboot_postgresql
    image: springboot_postgresql
    build:
      ./
    ports:
      - 8080:8080
    depends_on:
      - postgresqldbcnt
  postgresqldbcnt:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=parking-control-db