version: '3.1'
services:
  API:
    image: 'parking-control.jar'
    ports:
      - "8080:8080"
    depends_on:
      PostgresSQL:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/parking-control-db
      - SPRING_DATASOURCE_USERNAME=postgres
      -  SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PostgresSQL:
    image: postgres
    ports:
      - "5499:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5